name: build

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            dependencies-
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Checker prettier
        run: npm run prettier:check
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            dependencies-
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            dependencies-
      - name: Install dependencies
        run: npm ci && cd functions && npm ci
      - name: Build
        run: npm run build
