name: build

on: push

jobs:
  test-lint-build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - uses: actions/cache@v2.1.6
        id: npm-cache
        with:
          path: |
            ~/.npm
            ~/.cache/firebase/emulators
          key: euro-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            euro-dependencies-
      - name: Install dependencies
        run: npm ci
      - name: Install firebase-tools
        run: npm i firebase-tools@9 -g
      - name: Lint
        run: npm run lint
      - name: Lint function code
        run: npm run lint:functions
      - name: Check prettier
        run: npm run prettier:check
      - name: Unit tests
        run: npm test
      - name: Test Firebase rules
        run: npm run test:rules
      - name: Build
        run: npm run build
      - name: Publish built assets
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: euro-built
          path: build

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test-lint-build
    if: github.ref == 'refs/heads/master' # Run only on master

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - uses: actions/download-artifact@v2
        with:
          name: euro-built
          path: build
      - uses: actions/cache@v2.1.6
        id: npm-cache
        with:
          path: |
            ~/.npm
            ~/.cache/firebase/emulators
          key: euro-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            euro-dependencies-
      - name: Install dependencies
        run: npm ci && cd functions && npm ci
      - name: Install firebase-tools
        run: npm i firebase-tools@9 -g
      - name: Set firebase project
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase use default --token="$FIREBASE_TOKEN" --non-interactive
      - name: Firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token="$FIREBASE_TOKEN" --non-interactive --message "Deployment based on commit $(git rev-parse --short "$GITHUB_SHA")"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-lint-build
    if: github.ref == 'refs/heads/master' # Run only on master

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
      - uses: actions/cache@v2.1.6
        id: npm-cache
        with:
          path: |
            ~/.npm
            ~/.cache/firebase/emulators
          key: euro-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            euro-dependencies-
      - name: Install dependencies
        run: npm ci && cd functions && npm ci
      - name: Build
        run: npm run build:prod
      - name: Install firebase-tools
        run: npm i firebase-tools@9 -g
      - name: Set firebase project
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase use prod --token="$FIREBASE_TOKEN" --non-interactive
      - name: Firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token="$FIREBASE_TOKEN" --non-interactive --message "Deployment based on commit $(git rev-parse --short "$GITHUB_SHA")"
