name: build

on: push

jobs:
  test-lint-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: euro-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            euro-dependencies-
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check prettier
        run: npm run prettier:check
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Publish built assets
        uses: actions/upload-artifact@v2
        # if: github.ref == 'refs/heads/master'
        with:
          name: euro-built
          path: build

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test-lint-build
    # if: github.ref == 'refs/heads/master' # Run only on master

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - uses: actions/download-artifact@v2
        with:
          name: euro-built
          path: build
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: euro-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            euro-dependencies-
      - name: Install dependencies
        run: npm ci && cd functions && npm ci
      - name: Install firebase-tools
        run: npm i firebase-tools -g
      - name: Set firebase project
        run: firebase use default
      - name: Firebase deploy
        run: firebase deploy --token="$FIREBASE_TOKEN" --non-interactive
